### ISSUE TITLE
Docker compose up error: 'grep: /opt/bitnami/odoo/conf/odoo.conf: No such file or directory'

### ISSUE THREAD

**Issue by ict-scout-mv** [bitnami/bitnami-docker-odoo#113]
Here is my docker-compose.yml
```yaml
    version: '2'
    services:
      postgresql:
        user: root
        image: docker.io/bitnami/postgresql:13
        volumes:
          - ./postgresql_data:/bitnami/postgresql
        environment:
          - POSTGRESQL_USERNAME=bms
          - POSTGRESQL_DATABASE=odoo
          - POSTGRESQL_PASSWORD=xxx
      odoo:
        user: root
        image: docker.io/bitnami/odoo:15
        ports:
          - '80:8069'
        volumes:
          - ./odoo_data:/bitnami/odoo
          - ./odoo_addons:/bitnami/odoo/addons
        depends_on:
          - postgresql
        environment:
          - ODOO_EMAIL=x@y.com
          - ODOO_PASSWORD=xx
          - ODOO_LOAD_DEMO_DATA=yes
          - ODOO_DATABASE_HOST=postgresql
          - ODOO_DATABASE_PORT_NUMBER=5432
          - ODOO_DATABASE_USER=bms
          - ODOO_DATABASE_NAME=odoo
          - ODOO_DATABASE_PASSWORD=xxx
```
<img width="1279" alt="Screenshot 2021-12-27 at 18 50 42" src="https://user-images.githubusercontent.com/95347529/147477976-8d0d88ac-1ca8-46de-8485-32b1876880bf.png">

see lines ☝️
```
    server-odoo-1        | grep: /opt/bitnami/odoo/conf/odoo.conf: No such file or directory
    server-odoo-1 exited with code 2
```
This happens when I use volumes/folder mounts only. Works fine without any data persistence
