### ISSUE TITLE
Cannot configure SMTP parameters 

### ISSUE THREAD

**Issue by sameersbn** [bitnami/bitnami-docker-odoo#20]
specifying the SMTP parameter breaks the container initialization sequence with the following logs:

```
application_1  | nami    INFO  Initializing odoo
application_1  | odoo    INFO  Configuring Odoo database...
application_1  | odoo    INFO  Found Postgresql server listening at postgresql:5432
application_1  | odoo    INFO  Preparing Odoo environment...
application_1  | Error executing 'postInstallation': You should specify username, password, host, port for SMTP configuration
```

The following `docker-compose.yml` file can be used to reproduce the issus:

```yaml
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  application:
    image: 'bitnami/odoo:latest'
    ports:
      - '80:8069'
      - '443:8071'
    volumes:
      - 'odoo_data:/bitnami/odoo'
    depends_on:
      - postgresql
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_POR=587
      - SMTP_USER=mailman@example.com
      - SMTP_PASSWORD=secretpassword
      - SMTP_PROTOCOL=tls
volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
```
