### ISSUE TITLE
Multiple hosts in Ingress section of values.yaml

### ISSUE THREAD

**Issue by gridworkz** [bitnami/bitnami-docker-odoo#74]
I was able to consolidate the ingress annotations part and a few other things into a values.yaml file. See attached.

[values.zip](https://github.com/bitnami/bitnami-docker-odoo/files/3548063/values.zip)

I need to add 2 domains to the hosts: entry in the Ingress section but I can't get the syntax right. It's an array but I can't get it. How should that look in yaml? I tried a number of online yaml formatters but no luck. I'm trying to do the www redirect to root thing. Also, it seems in GKE I need a certificate and issuer on the cluster first before I run the Helm chart. No biggy. It kept warning about no cluster issuer found so I needed to issue a customer cert on the cluster and all good.

**Comment by miguelaeh** [comment]
Hi @gridworkz ,
Thank you very much for reporting!!!, it was an issue with the ingress template, your `values.yaml` is perfectly valid.
Check [this PR](https://github.com/helm/charts/pull/16645).

**Comment by miguelaeh** [comment]
Hi @gridworkz,
The syntax is the second one but the PR is not merged yet.
Please, wait until the PR will be merged and update your repositories once it is merged.

**Comment by gridworkz** [comment]
oops, my apologies.
Cheers,
Dave

**Comment by gridworkz** [comment]
Some things deploy (workloads, services) but I get this error:

Error: release skunkhollowbud-com-odoo failed: Ingress.extensions "skunkhollowbud-com-odoo" is invalid: spec.tls[0].hosts: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

...then no Ingress is created on the GKE side. Using the second syntax from above.

**Comment by miguelaeh** [comment]
Hi @gridworkz ,
Please update your helm repositories in order to take the latest changes, yesterday a major version of the chart was released.
It works in this way:
```  139 ingress:
  140   ## Set to true to enable ingress record generation
  141   enabled: false
  142
  143   ## The list of hostnames to be covered with this ingress record.
  144   ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  145   hosts:
~ 146   - name: skunkhollowbud.com
+ 147     path: /
+ 148   - name: www.skunkhollowbud.com
  149     path: /
  150
```
As you can see:
```
7:10:20 › kubectl get ingress
NAME               HOSTS                                       ADDRESS            PORTS     AGE
dp-osclass-sgg2z   dp-osclass-sgg2z.c101.k.pks.bitnami.net     35.194.66.96,...   80, 443   15h
odoo               skunkhollowbud.com,www.skunkhollowbud.com   35.194.66.96,...   80, 443   1m
```

**Comment by gridworkz** [comment]
Great, thanks! Forgot to update....
Cheers,
Dave

**Comment by gridworkz** [comment]
Cool, I got two hosts now in the Ingress rules spec but only one TLS: host. Do I need to add something to the values.yaml for that?

[shb-odoo-ingress.zip](https://github.com/bitnami/bitnami-docker-odoo/files/3560763/shb-odoo-ingress.zip)

**Comment by miguelaeh** [comment]
I should be enought with something like this:
```
hosts:
  - name: skunkhollowbud.com
     path: /
     tls: true
     tlsSecret: your-secret-name
  - name: www.skunkhollowbud.com
     path: /
     tls: true
     tlsSecret: your-secret-name```

Did you set the values in that way?

**Comment by gridworkz** [comment]
Hi Miguel:

Thanks, I didn't have the extra TLS stuff.

Cheers,
Dave

**Comment by gridworkz** [comment]
Hi Miguel:

I got this error after adding the TLS stuff:

Error: YAML parse error on odoo/templates/ingress.yaml: error converting
YAML to JSON: yaml: line 31: did not find expected key

The yaml is perfectly valid (I tested it - line #31 is a comment anyway).

Cheers,
Dave

**Comment by miguelaeh** [comment]
Hi @gridworkz ,
please provide the command you are using to deploy it. I cannot get that error. Have you modified the yaml files?
Can you check the installation with `helm template` to see the YAMLs?

**Comment by gridworkz** [comment]
Hi Miguel:

Cool, I just wanted to know if you got that error. Obviously something on
my side is not quite right. Thanks for checking, I'll some more testing on
my side.

Cheers,
Dave

**Comment by miguelaeh** [comment]
Hi @gridworkz ,
Okay, feel free to ask whatever you need.
Cheers.

**Comment by gridworkz** [comment]
Hi Miguel:

Here's my values.yaml file. I still get errors when running it. The error
is:

Error: failed to parse /home/ubuntu/gridworkz/cooby.org/values.yaml: error
converting YAML to JSON: yaml: line 147: mapping values are not allowed in
this context

I run this in a bash script and all the substitution variables work fine. I
tried hard coding values as well with the same result.

Cheers,
Dave

**Comment by gridworkz** [comment]
I did some further testing with the template method and here's my output (using my current values.yaml file):

```
# Source: odoo/templates/ingress.yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: release-name-odoo
  labels:
    app: odoo
    chart: odoo-11.1.1
    release: "release-name"
    heritage: "Tiller"
  annotations:
spec:
  rules:
  - host: www.skunkhollowbud.com
    http:
      paths:
        - path: /
          backend:
            serviceName: release-name-odoo
            servicePort: http
  - host: skunkhollowbud.com
    http:
      paths:
        - path: /
          backend:
            serviceName: release-name-odoo
            servicePort: http
  tls:
  - hosts:

    - www.skunkhollowbud.com
    secretName: skunkhollowbud-com-tls-prod
    - skunkhollowbud.com
    secretName: skunkhollowbud-com-tls-prod
```
If I check this yaml online it errors out with:

Error : You cannot define a sequence item when in a mapping
Line : undefined  undefined

If I manually change the order of the tls stuff like this: 
```
# Source: odoo/templates/ingress.yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: release-name-odoo
  labels:
    app: odoo
    chart: odoo-11.1.1
    release: "release-name"
    heritage: "Tiller"
  annotations:
spec:
  rules:
  - host: www.skunkhollowbud.com
    http:
      paths:
        - path: /
          backend:
            serviceName: release-name-odoo
            servicePort: http
  - host: skunkhollowbud.com
    http:
      paths:
        - path: /
          backend:
            serviceName: release-name-odoo
            servicePort: http
  tls:
  - hosts:
    - www.skunkhollowbud.com
    - skunkhollowbud.com
    secretName: skunkhollowbud-com-tls-prod
```
The yaml passes.
