### ISSUE TITLE
Password authentication failed for user "bn_odoo"

### ISSUE THREAD

**Issue by HarlekinSimplex** [bitnami/bitnami-docker-odoo#78]
Hi Bitnami Docker Team.
I've a problem with bitnami/odoo:13 on bitnami/postgresql:11

**Description**
During 'sudo docker-compose up' the installation terminates with the the following error messages:

Odoo:
psycopg2.OperationalError: FATAL:  password authentication failed for user "**bn_odoo**"

Postgresql:
[206] FATAL  password authentication failed for user "bn_odoo"
[206] DETAIL:  Role "**bn_odoo**" does not exist.

Looks like the user 'bn_odoo' has not been created prior using it....
Any idea whats wrong with my docker-compose.yml ?

Cheers
Stephan

**Steps to reproduce the issue:**
Just basic install of both containers with the following docker-compose
(I run docker in my Synology NAS)
 
```
bsb-dev_postgresql11:
    container_name: bsb-dev_postgresql11
    image: 'bitnami/postgresql:latest'
    ports:
      - '5132:5432'
    networks:
      - development
    environment:
      - POSTGRESQL_PASSWORD=odoo
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/volume1/docker/bsb-odoo/dev/bsb-dev_postgresql:/bitnami'
    depends_on:
      - bsb-dev_postgresql11_permission-fix
      
  bsb-dev_postgresql11_permission-fix:
    container_name: bsb-dev_postgresql11_permission-fix
    image: 'bitnami/postgresql:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - '/volume1/docker/bsb-odoo/dev/bsb-dev_postgresql:/bitnami'
  
  bsb-dev_odoo13:
    container_name: bsb-dev_odoo13
    image: 'bitnami/odoo:13'
    ports:
      - '8180:8069'
      - '8171:8071'
    networks:
      - development
    links:
      - "bsb-dev_postgresql11:postgresql"
    environment:
      - POSTGRESQL_PASSWORD=odoo
      - ODOO_EMAIL=test.admin@xxxxx
      - ODOO_PASSWORD=xxxxx
    volumes:
      - '/volume1/docker/bsb-odoo/dev/bsb-dev_odoo:/bitnami'
      - '/volume1/docker/bsb-odoo/dev/bsb-dev_odoo_scripts:/bsb-scripts'
    depends_on:
      - bsb-dev_postgresql11
      - bsb-dev_odoo13_permission-fix
      
  bsb-dev_odoo13_permission-fix:
    container_name: bsb-dev_odoo13_permission-fix
    image: 'bitnami/odoo:13'
    user: root
    command: chown -R odoo:odoo /bitnami
    volumes:
      - '/volume1/docker/bsb-odoo/dev/bsb-dev_odoo:/bitnami'

networks:
    development:
        driver: bridge


```
