### ISSUE TITLE
Unable to start com.bitnami.odoo: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'

### ISSUE THREAD

**Issue by qwertmax** [bitnami/bitnami-docker-odoo#82]
I'm trying to start `odoo` with RDS as storage.

docker start command:

```bash
docker run \
--rm \
-it \
-p 8069:8069 \
--name odoo \
-e POSTGRESQL_HOST="xxxxx.rds.amazonaws.com" \
-e POSTGRESQL_PORT_NUMBER="5432" \
-e POSTGRESQL_PASSWORD="xxxxxx" \
-e POSTGRESQL_USER="postgres" \
-e ODOO_EMAIL="example@mail.com" \
-e ODOO_PASSWORD="admin" \
bitnami/odoo:13
```

output:

```bash
Error executing 'postInstallation': Unable to start com.bitnami.odoo: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'.: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'.
```

output with debug trace:

```bash
nami    TRACE Error: Error executing 'postInstallation': Unable to start com.bitnami.odoo: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'.: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'.
    at Service._execServiceCommand (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:162:15)
    at Service._start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:348:12)
    at Service.start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:376:30)
    at Service.$app.postInstallation (/root/.nami/components/com.bitnami.odoo/main.js:56:10)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
```

What am I missing ?

**Comment by javsalgar** [comment]
Hi,

It seems that odoo is crashing trying to access RDS. Does the issue happen with the example docker-compose.yml that we have in our repository?

**Comment by qwertmax** [comment]
@javsalgar  yes, it also crashed with exactly the same error. 

my docker-compose.yml

```yml
version: '2'
services:
  odoo:
    image: 'bitnami/odoo:13'
    ports:
      - '80:8069'
      - '443:8071'
    volumes:
      - 'odoo_data:/bitnami'
    environment:
      - POSTGRESQL_HOST=xxxxx.rds.amazonaws.com
      - POSTGRESQL_PORT_NUMBER=5432
      - POSTGRESQL_PASSWORD=xxxxxx
      - POSTGRESQL_USER=postgres
      - ODOO_EMAIL=example@mail.com
      - ODOO_PASSWORD=admin

volumes:
  odoo_data:
    driver: local
```

Output:

```bash
docker-compose logs -f
Attaching to bitnami-docker-odoo_odoo_1
odoo_1  |
odoo_1  | Welcome to the Bitnami odoo container
odoo_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
odoo_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues
odoo_1  | Send us your feedback at containers@bitnami.com
odoo_1  |
odoo_1  | nami    INFO  Initializing odoo
odoo_1  | odoo    INFO  Configuring Odoo database...
odoo_1  | postgre INFO  Trying to connect to PostgreSQL server
odoo_1  | postgre INFO  Found PostgreSQL server listening at xxx.rds.amazonaws.com:5432
odoo_1  | postgre INFO  PostgreSQL server listening and working at xxx.rds.amazonaws.com:5432
odoo_1  | odoo    INFO  Preparing Odoo environment...
odoo_1  | odoo    INFO  Starting Odoo...
odoo_1  | Error executing 'postInstallation': Unable to start com.bitnami.odoo: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'.: Cannot find pid file '/opt/bitnami/odoo/tmp/pids/odoo.pid'.
bitnami-docker-odoo_odoo_1 exited with code 1
```

have you any idea what could it be?
