### ISSUE TITLE
Odoo freezes while "Trying to connect to PostgreSQL server" if services' names are changed.

### ISSUE THREAD

**Issue by pekechis** [bitnami/bitnami-docker-odoo#92]
**Environment**
Ubuntu 20.04
Docker version 19.03.8
Docker-compose version 1.25.0

The docker-compose.yml starts without any problem with the default content(only http port number changed
) but if I aditionally  change the services' names the up process freezes with the following message:

"Trying to connect to PostgreSQL server"

```yml

version: '2'
services:
  servicio1:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  servicio2:
    image: 'docker.io/bitnami/odoo:13-debian-10'
    ports:
      - '9090:8069'
      - '443:8071'
    volumes:
      - 'odoo_data:/bitnami'
    depends_on:
      - servicio1
volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
```

Seems to me that maybe it's an error in the Dockerfile.

Thanks in advance

**Comment by miguelaeh** [comment]
Hi @pekechis ,
You need to configure the `postgresql-host` as explained at https://github.com/bitnami/bitnami-docker-odoo#environment-variables

**Comment by pekechis** [comment]
Hi @miguelaeh ,

Not working, even if I use POSTGRESQL_HOST:servicio1 as this:

```yml
version: '2'
services:
  servicio1:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  servicio2:
    image: 'docker.io/bitnami/odoo:13-debian-10'
    environment: 
      - POSTGRESQL_HOST:servicio1
    ports:
      - '9090:8069'
      - '443:8071'
    volumes:
      - 'odoo_data:/bitnami'
    depends_on:
      - servicio1
volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
```

Still freezes when "Trying to connect to the database" even when I change the host of the service. 

I'm supposing that the default values for the other environment vars are kept and configured correctly.

**Comment by miguelaeh** [comment]
The following docker-compose worked for me:
```
version: '2'
services:
  servicio1:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  odoo:
    image: 'docker.io/bitnami/odoo:13-debian-10'
    environment:
      - 'POSTGRESQL_HOST=servicio1'
    ports:
      - '80:8069'
      - '443:8071'
    volumes:
      - 'odoo_data:/bitnami'
    depends_on:
      - servicio1
volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
```
